eos/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

#from django.conf.urls import url

urlpatterns = [

    path('portal/', include('portal.urls')),
    #path('portal/portal', include('portal.urls')),
    path('registration/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    #url(r'^accounts/login/$', 'django.contrib.auth.views.login', name='login'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #this might not be necessary

portal/urls.py
from django.urls import path
from django.views.generic.base import TemplateView # new

from . import views

#from django.conf.urls import url

app_name = 'portal'

urlpatterns = [

    #path('login/', views.login, name='login'),
    path('nhis_form/', views.nhis_form, name='nhis_form'),
    path('pocket_guide/', views.pocket_guide, name='pocket_guide'),
    path('personal_details/', views.personal_details, name='personal_details'),
    path('', views.home, name='home'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('is/', views.ISView.as_view(), name='is'),
    path('hr/', views.HRView.as_view(), name='hr'),
    path('employees/', views.EmployeesView.as_view(), name='employees'),
    path('forms/', views.FormsView.as_view(), name='forms'),
    path('todo/', views.TodoView.as_view(), name='todo'),
    path('tutorials/', views.TutorialsView.as_view(), name='tutorials'),

]

portal/models.py
from django.db import models

from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.utils.translation import gettext_lazy as _
from django.utils import timezone
from django.db.models.functions import Concat
from django.db.models import CharField, Value

from .managers import CustomUserManager

"""
Extracted from <https://testdriven.io/blog/django-custom-user-model/>
"""


"""
CHANGE THE FOLLOWING SO THAT IT IS TIED INTO THE DEPARTMENT MODEL
"""
DEPARTMENTS = [
        ('IS', 'Information Systems'),
        ('HR', 'Human Resources'),
        ('EHS', 'Environment, Health, and Safety'),
        ('F', 'Facilities'),
        ('SC', 'Supply Chain'),
        ('T', 'Telecommunications'),
        ('ENG', 'Engineering')
    ]

def get_department():
    return Department.objects.get(id=1)

DEFAULT_DEPARTMENT_ID = 1
"""
class FullNameField(models.Field):

    def __init__(self, first_name, last_name, *args, **kwargs):
        self.first_name = str(first_name)
        self.last_name = str(last_name)
        self.exp_field = kwargs.pop('exp_field', None)
        kwargs['max_length'] = 104
        super().__init__(*args, **kwargs)

    def deconstruct(self):
        name, path, args, kwargs = super().deconstruct()
        del kwargs["max_length"]
        return name, path, args, kwargs

    def get_full_name(self):
        return self.first_name + " " + self.last_name
"""

class Department(models.Model):
    """
    This is the Department model, which represents one department added to the database i.e.
    every department is an instance of our Department model
    """

    dept_name = models.CharField(max_length=200)

    def __str__(self):
        return self.dept_name

class CustomUser(AbstractBaseUser, PermissionsMixin):
    """
    This is our user model which inherits from Django's built-in AbstractBaseUser model
    """
    email = models.EmailField(_('email address'), unique=True)
    is_staff = models.BooleanField(_('staff'), default=False)
    is_active = models.BooleanField(_('active'),default=True)
    date_joined = models.DateTimeField(default=timezone.now)
    full_name = models.CharField(_('full name'), max_length=41, default="Full Name")
    #full_name = FullNameField(first_name=first_name, last_name=last_name, max_length=41).get_full_name()
    #full_name = Concat('first_name', Value(' '), 'last_name', output_field=CharField())

    dept = models.ForeignKey(Department, default=DEFAULT_DEPARTMENT_ID, on_delete=models.CASCADE)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email


def user_directory_path(instance, filename):
    """
    This function creates the name of the directory that a video object with a file upload
    will be saved to.
    TODO: Make this more robust i.e. deal with department names that have things like "and",
    commas, etc
    """

    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    dept_token_list = instance.dept.dept_name.split(' ')
    dept = ''
    for word in dept_token_list:
        dept += word[0].lower()
    return '{0}/{1}'.format(dept,filename)

class Video(models.Model):
    """
    This is the Video model, which represents one video added to the database i.e. every
    video is an instance of our Video model
    """

    """
    TODO: Change Video to have a many-to-many relationship with Department so that one video
    can belong to multiple departments
    """
    dept = models.ForeignKey(Department, on_delete=models.CASCADE)
    video_name = models.CharField(max_length=200)
    video_url = models.URLField(max_length=200, blank=True)
    video_upload = models.FileField(upload_to=user_directory_path, blank=True)
    description = "Here is a nice description that someone did not have time to type up"
    video_description = models.TextField(blank=True, default = description)

    def __str__(self):
        return self.video_name

class Resource(models.Model):
    """
    to be added in later versions
    """
    pass

portal/forms.py
"""
Extracted from <https://testdriven.io/blog/django-custom-user-model/>
"""
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
"""
To use the PhoneNumberField, make sure you've installed the phonenumber_field library with
pip install django-phonenumber-field
Found at <https://stackoverflow.com/questions/19130942/whats-the-best-way-to-store-phone-number-in-django-models>
"""
#from phonenumber_field.modelfields import PhoneNumberField
from django import forms
from .models import CustomUser

from django.core.validators import RegexValidator

"""
TODO: Ask Human Resources what other forms are able to be completed electronically
"""

class PersonalDetailsForm(forms.Form):
    """
    TODO: Check to see what info Human Resources needs from a personal details form
    """
    first_name = forms.CharField(label='First name', max_length=24, required=True)
    last_name = forms.CharField(label='Last name', max_length=24, required=True)
    #phone_number = PhoneNumberField()  //Check why no module named 'phonenumbers'
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    phone_number = forms.CharField(validators=[phone_regex], max_length=17, required=True) # validators should be a list
    virtual_address = forms.CharField(label='Address', max_length=128, required=False, widget=forms.Textarea)
    post_office_box = forms.CharField(label='P.O. Box', max_length=24, required=False)

class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm):
        model = CustomUser
        fields = ('email', 'full_name', )


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('email', 'full_name', 'is_staff', )

portal/views.py
from django.shortcuts import render
from django.http import Http404, HttpResponse, FileResponse, HttpResponseRedirect

from django.urls import reverse_lazy
from django.views import generic

#from django.contrib.auth import authenticate, login

from .models import CustomUser, Department
from .forms import CustomUserCreationForm

from .forms import PersonalDetailsForm

def nhis_form(request):
    """
    The view for the HR Pocket Guide (use this generally for pdf documents)
    """
    with open('portal/nhis_form.pdf', 'rb') as pdf:
        response = HttpResponse(pdf.read(), content_type='application/pdf')
        response['Content-Disposition'] = 'inline;filename=nhis_form.pdf'
        return response


def pocket_guide(request):
    """
    The view for the HR Pocket Guide (use this generally for pdf documents)
    """
    with open('portal/pocket_guide.pdf', 'rb') as pdf:
        response = HttpResponse(pdf.read(), content_type='application/pdf')
        response['Content-Disposition'] = 'inline;filename=pocket_guide.pdf'
        return response

def details(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = PersonalDetailsForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            """
            TODO: process the data in form.cleaned_data as required
            """
            # redirect to a new URL:
            return HttpResponseRedirect('../forms/')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = PersonalDetailsForm()

    return render(request, 'portal/details.html', {'form': form})

def personal_details(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = PersonalDetailsForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            """
            TODO:process the data in form.cleaned_data as required
            """
            # redirect to a new URL:
            return HttpResponseRedirect('../forms/')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = PersonalDetailsForm()

    return render(request, 'portal/personal_details.html', {'form': form})

class EmployeesView(generic.ListView):
    template_name = 'portal/employees.html'
    context_object_name = 'is_video_list'

    def get_queryset(self):
        """
        """
        dept = Department.objects.get(dept_name="Information Systems")
        return dept.video_set.all()

class FormsView(generic.ListView):
    template_name = 'portal/forms.html'
    context_object_name = 'is_video_list'

    def get_queryset(self):
        """
        """
        dept = Department.objects.get(dept_name="Information Systems")
        return dept.video_set.all()

class TodoView(generic.ListView):
    template_name = 'portal/todo.html'
    context_object_name = 'is_video_list'

    def get_queryset(self):
        """
        """
        dept = Department.objects.get(dept_name="Information Systems")
        return dept.video_set.all()


class TutorialsView(generic.ListView):
    template_name = 'portal/tutorials.html'
    context_object_name = 'user_video_list'

    def get_queryset(self):
        """
        """
        user = self.request.user
        dept = user.dept
        return dept.video_set.all()

class SignUpView(generic.CreateView):

    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'portal/signup.html'

class ISView(generic.ListView):
    template_name = 'portal/is.html'
    context_object_name = 'is_video_list'

    def get_queryset(self):
        """
        """
        dept = Department.objects.get(dept_name="Information Systems")
        return dept.video_set.all()

class HRView(generic.ListView):
    template_name = 'portal/hr.html'
    context_object_name = 'hr_video_list'

    def get_queryset(self):
        """
        """
        dept = Department.objects.get(dept_name="Human Resources")
        return dept.video_set.all()
"""
TODO: Test login redirect on incorrect Information

def login(request):

    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            login(request, user)
            url = reverse('pilot:home')
            return HttpResponseRedirect(url)
    else:
        form = LoginForm()
    return render(request, 'login.html', {'form':form})

    ORRR?

    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        url = reverse('portal:tutorials')
        return HttpResponseRedirect(url)
    else:
        # Return an 'invalid login' error message.

    #return render(request, 'portal/login.html')
"""
def login(request):

    return render(request, 'portal/login.html')

def home(request):

    return render(request, 'portal/home.html')

portal/templates/portal/email.html
{% if user.is_authenticated %}
  <p>{{ user.email|lower }}</p>
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">login</a>
{% endif %}

portal/templates/portal/forms.html
{% load static %}

<!DOCTYPE html>
<html lang="zxx">

<head>
	<title>Tullow Oil Ghana | Forms to Fill</title>
	<!-- Meta tag Keywords -->
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta charset="UTF-8" />
	<meta name="keywords" content="Tullow Oil Ghana" />
	<script>
		addEventListener("load", function () {
			setTimeout(hideURLbar, 0);
		}, false);

		function hideURLbar() {
			window.scrollTo(0, 1);
		}
	</script>
	<!-- //Meta tag Keywords -->

	<!-- Custom-Files -->
	<link rel="stylesheet" href="{% static 'portal/css/bootstrap.css' %}">
	<!-- Bootstrap-Core-CSS -->
	<link rel="stylesheet" href="{% static 'portal/css/style.css' %} " type="text/css" media="all" />
	<!-- Style-CSS -->
	<link href="{% static 'portal/css/font-awesome.min.css' %}" rel="stylesheet">
	<!-- Font-Awesome-Icons-CSS -->
	<!-- //Custom-Files -->

	<!-- Web-Fonts -->
	<link href="//fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&amp;subset=devanagari,latin-ext"
	 rel="stylesheet">
	<!-- //Web-Fonts -->

	<style>
		.dropbtn {
			background-color: #3498DB;
			color: white;
			padding: 16px;
			font-size: 16px;
			border: none;
			cursor: pointer;
		}

		.dropbtn:hover, .dropbtn:focus {
			background-color: #2980B9;
		}

		.dropdown {
			position: relative;
			display: inline-block;
		}

		.dropdown-content {
			display: none;
			position: absolute;
			background-color: #f1f1f1;
			min-width: 160px;
			overflow: auto;
			box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
			z-index: 1;
		}

		.dropdown-content a {
			color: black;
			padding: 12px 16px;
			text-decoration: none;
			display: block;
		}

		.dropdown a:hover {background-color: #ddd;}

		.show {display: block;}
	</style>

</head>

<body>
	<!-- main banner -->
	<div class="main-top" id="home">
		<!-- header -->
		<header>
			<div class="container-fluid">
				<div class="header d-lg-flex justify-content-between align-items-center py-3 px-sm-3">
					<!-- logo -->
					<div id="logo">
						<h1><a href="#"><span class="fa fa-linode mr-2"></span>Tullow Oil Ghana</a></h1>
					</div>
					<!-- //logo -->
					<!-- nav -->
					<div class="nav_w3ls">
						<nav>
							<label for="drop" class="toggle">Menu</label>
							<input type="checkbox" id="drop" />
							<ul class="menu">
								<li><a href="{% url 'portal:tutorials' %}" >Tutorials & Videos</a></li>
								<li><a href="{% url 'portal:forms' %}" class="active">Forms to Fill</a></li>
								<li><a href="{% url 'portal:todo' %}" >Todo List & Resources</a></li>
								<li><a href="{% url 'portal:employees' %}" >Other Employess</a></li>
							</ul>
						</nav>
					</div>
					<!-- //nav -->
					<div class="d-flex mt-lg-1 mt-sm-2 mt-3 justify-content-center">

						<!-- download
						<a class="dwn-w3ls btn" href="#">
							<span class="fa fa-user"></span>
						</a>
						a href="javascript:openwindow()
						-->

						<div class="dropdown">
							<a class="dropbtn" href="javascript:myFunction()">
								<span class="fa fa-user"></span>
							</a>
							<div id="myDropdown" class="dropdown-content">
								<a href="#">{{user.full_name}}</a>
								<a href="#settings">Settings</a>
								<a href="{% url 'logout' %}">Logout</a>
							</div>
						</div>

						<script>
							/* When the user clicks on the button,
							toggle between hiding and showing the dropdown content */
							function myFunction() {
								document.getElementById("myDropdown").classList.toggle("show");
							}

							// Close the dropdown if the user clicks outside of it
							window.onclick = function(event) {
								if (!event.target.matches('.dropbtn')) {
									var dropdowns = document.getElementsByClassName("dropdown-content");
									var i;
									for (i = 0; i < dropdowns.length; i++) {
										var openDropdown = dropdowns[i];
										if (openDropdown.classList.contains('show')) {
											openDropdown.classList.remove('show');
										}
									}
								}
							}
						</script>
						<!-- //download -->
					</div>
				</div>
			</div>
		</header>
		<!-- //header -->

		<!-- banner -->
		<div class="banner_w3lspvt-2">
			<ol class="breadcrumb">
				<li class="breadcrumb-item"><a href="#" class="font-weight-bold">Home</a></li>
				<li class="breadcrumb-item" aria-current="page">Forms to Fill</li>
			</ol>
		</div>
		<!-- //banner -->
	</div>
	<!-- //main banner -->
	<div class="price-sec py-5">
		<div class="container py-xl-5 py-lg-3">
			<div class="inner_sec_info_w3_info mt-3">
				<div class="row price-grid-main">
					<div class="col-lg-3 col-sm-6 price-info">
						<div class="prices p-4">
							<div class="prices-bottom text-center">
								<div class="prices-h border-bottom p-4">
									<h4>NHIS</h4>
								</div>
								<a href="{% url 'portal:nhis_form' %}" class="btn button-style mt-4">Fill Form</a>
							</div>
						</div>
					</div>
					<div class="col-lg-3 col-sm-6  price-info price-mkres-2">
						<div class="prices p-4 active">
							<div class="prices-bottom text-center">
								<div class="prices-h border-bottom p-4">
									<h4>SSNIT</h4>
								</div>
								<a href="#" class="btn button-style mt-4">Fill Form</a>
							</div>
						</div>
					</div>
					<div class="col-lg-3 col-sm-6  price-info price-mkres">
						<div class="prices p-4">
							<div class="prices-bottom text-center">
								<div class="prices-h border-bottom p-4">
									<h4>Personal Details</h4>
								</div>
								<a href="{% url 'portal:personal_details' %}" class="btn button-style mt-4">Fill Form</a>
							</div>
						</div>
					</div>
					<div class="col-lg-3 col-sm-6  price-info price-mkres">
						<div class="prices p-4 active">
							<div class="prices-bottom text-center">
								<div class="prices-h border-bottom p-4">
									<h4>Details</h4>
								</div>
								<a href="#" class="btn button-style mt-4">Fill Form</a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- copyright bottom -->
	<div class="copy-bottom bg-li py-4 border-top">
		<div class="container-fluid">
			<div class="d-md-flex px-md-3 position-relative text-center">
				<!-- footer social icons -->
				<div class="social-icons-footer mb-md-0 mb-3">
					<ul class="list-unstyled">
						<li>
							<a href="#">
								<span class="fa fa-facebook"></span>
							</a>
						</li>
						<li>
							<a href="#">
								<span class="fa fa-twitter"></span>
							</a>
						</li>
						<li>
							<a href="#">
								<span class="fa fa-google-plus"></span>
							</a>
						</li>
						<li>
							<a href="#">
								<span class="fa fa-instagram"></span>
							</a>
						</li>
					</ul>
				</div>
				<!-- //footer social icons -->
				<!-- copyright -->
				<div class="copy_right mx-md-auto mb-md-0 mb-3">
					<p class="text-bl let">© 2019 Tullow Oil Ghana. All rights reserved | Powered by
						<a href="#" target="_blank">OI</a>
					</p>
				</div>
				<!-- //copyright -->
				<!-- move top icon -->
				<a href="#home" class="move-top text-center">
					<span class="fa fa-level-up" aria-hidden="true"></span>
				</a>
				<!-- //move top icon -->
			</div>
		</div>
	</div>
	<!-- //copyright bottom -->

</body>

</html>

portal/templates/portal/home.html
{% extends "portal/base.html" %}
{% block content %}

<div>
  <p>TESTING</p>
</div>

{% endblock %}

portal/templates/portal/hr.html
{% extends "portal/base.html" %}
{{ request.get_full_path }}
{% block content %}

  {% if hr_video_list %}
    <ul>
      {% for video in hr_video_list %}
        <h2> {{ video.video_name|title }} </h2>
        <p> {{ video.video_upload.url }} </p>
        <div>
          <video width="320" height="240" controls>
            <source src="portal:{{ video.video_upload.url }}" type="video/mp4">

            Your browser does not support the video tag.
          </video>
        </div>
      {% endfor %}
    </ul>
  {% else %}
    <p>No HR videos are available.</p>
  {% endif %}
{% endblock %}

portal/templates/portal/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
   <head>
      <title>Tullow Oil Ghana | Login</title>
      <!-- Meta tags -->
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
      <meta name="keywords" content="Tullow Oil Ghana"
         />
      <script>
         addEventListener("load", function () { setTimeout(hideURLbar, 0); }, false); function hideURLbar() { window.scrollTo(0, 1); }
      </script>
      <!-- Meta tags -->
      <!--stylesheets-->
      <link href="{% static 'portal/css/login/style1.css' %}" rel='stylesheet' type='text/css' media="all">
      <!--//style sheet end here-->
      <link href="//fonts.googleapis.com/css?family=Source+Sans+Pro:400,600,700" rel="stylesheet">
   </head>
   <body>
      <div class="mid-class">
         <div class="art-right-w3ls">
            <h2>Login</h2>
            <form action="portal/home.html" method="post">
              {% csrf_token %}
              <div class="{% static 'portal/css/login/style1.css' %}">
                  <div class="form-left-to-w3l">
                     <input type="text" name="name" placeholder="Username" required="">
                  </div>
                  <div class="form-left-to-w3l ">
                     <input type="password" name="password" placeholder="Password" required="">
                     <div class="clear"></div>
                  </div>
               </div>
               <div class="left-side-forget">
                  <input type="checkbox" class="checked">
                  <span class="remenber-me">Remember me </span>
               </div>
               <div class="right-side-forget">
                  <a href="#" class="for">Forgot password...?</a>
               </div>
               <div class="clear"></div>
               <div class="btnn">
                  <button type="submit">Sign In</button>
               </div>
            </form>
            <div class="w3layouts_more-buttn">
               <h3>Don't Have an account..?
                  <a href="#content1">Sign Up Here
                  </a>
               </h3>
            </div>
            <!-- popup-->
            <div id="content1" class="popup-effect">
               <div class="popup">
                  <!--login form-->
                  <div class="letter-w3ls">
                     <form action="#" method="post">
                       {% csrf_token %}
                        <div class="form-left-to-w3l">
                           <input type="text" name="name" placeholder="Username" required="">
                        </div>
                        <div class="form-left-to-w3l">
                           <input type="text" name="name" placeholder="Phone" required="">
                        </div>
                        <div class="form-left-to-w3l">
                           <input type="email" name="email" placeholder="Email" required="">
                        </div>
                        <div class="form-left-to-w3l">
                           <input type="password" name="password" placeholder="Password" required="">
                        </div>
                        <div class="form-left-to-w3l margin-zero">
                           <input type="password" name="password" placeholder="Confirm Password" required="">
                        </div>
                        <div class="btnn">
                           <button type="submit">Sign Up</button>
                           <br>
                        </div>
                     </form>
                     <div class="clear"></div>
                  </div>
                  <!--//login form-->
                  <a class="close" href="#">&times;</a>
               </div>
            </div>
            <!-- //popup -->
         </div>
         <div class="art-left-w3ls">
            <h1 cass="header-w3ls">
            <div style="text-align: center">
              <img src="{% static 'portal/images/login/original.jpg' %}" height="100px" />
              </div>
         </div>
      </div>
      <footer class="bottem-wthree-footer">
         <p>
            © 2019 Tullow Oil Ghana. All Rights Reserved | Powerd by
            <a href="#" target="_blank">OI</a>
         </p>
      </footer>
   </body>
</html>

portal/templates/portal/is.html
{% extends "portal/base.html" %}
{% block content %}

  {% if is_video_list %}
    <ul>
      {% for video in is_video_list %}
        <h2> {{ video.video_name|title }} </h2>
        <div>
          <iframe width="560" height="315" src="{{ video.video_url }}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        </div>
      {% endfor %}
    </ul>
  {% else %}
    <p>No IS videos are available.</p>
  {% endif %}
{% endblock %}

portal/templates/portal/login.html
<!-- Extracted from <https://wsvincent.com/django-user-authentication-tutorial-login-and-logout/> -->
<h2>Login</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Login</button>
</form>

portal/templates/portal/personal_details.html
<form action="{% url 'portal:personal_details' %}" method="post">
  {% csrf_token %}
  {{ form.non_field_errors }}
  <div class="fieldWrapper">
      {{ form.first_name.errors }}
      <label for="{{ form.first_name.id_for_label }}">First Name:</label>
      {{ form.first_name }}
  </div>
  <div class="fieldWrapper">
      {{ form.last_name.errors }}
      <label for="{{ form.last_name.id_for_label }}">Last Name:</label>
      {{ form.last_name }}
  </div>
  <div class="fieldWrapper">
      {{ form.phone_number.errors }}
      <label for="{{ form.phone_number.id_for_label }}">Phone Number:</label>
      {{ form.phone_number }}
  </div>
  <div class="fieldWrapper">
      {{ form.virtual_address.errors }}
      <label for="{{ form.virtual_address.id_for_label }}">Address</label>
      {{ form.virtual_address }}
  </div>
  <div class="fieldWrapper">
      {{ form.post_office_box.errors }}
      <label for="{{ form.post_office_box.id_for_label }}">P.O. Box</label>
      {{ form.post_office_box }}
  </div>
  <button type="submit">Submit</button>
</form>
<!--
<form action="/personal_details/" method="post">
    {% csrf_token %}
    {{ form.as_table }}
    <input type="submit" value="Submit">
</form>
-->

portal/templates/portal/signup.html
{% block title %}Sign Up{% endblock %}

  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
  </form>